import type { ArticleMeta } from "./types";

/**
 * Central content registry. Every article on the site — published or
 * planned — has one entry here. Pillar index pages render "published"
 * entries as live cards and "coming-soon" entries as a disabled card, so
 * nothing in the roadmap ever produces a dead link.
 */
export const ARTICLES: ArticleMeta[] = [
  // ---------------------------------------------------------------- AI Legal Tools
  {
    slug: "best-ai-legal-tools-2026",
    pillar: "ai-legal-tools",
    href: "/ai-legal-tools/best-ai-legal-tools-2026/",
    title: "Best AI Legal Tools in 2026: Tested and Ranked",
    seoTitle: "Best AI Legal Tools in 2026: Tested and Ranked | LexAI Guide",
    metaDescription:
      "We tested the leading AI legal tools for contract review, LLC formation, and consumer disputes. Here's what's actually worth paying for in 2026.",
    dek: "We tested the leading AI legal tools so you don't have to guess which one earns its subscription.",
    intent: "comparative",
    keywordDifficulty: 28,
    estRpm: 42,
    status: "published",
    readingTime: 13,
    datePublished: "2026-01-12",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,800–3,500 words",
  },
  {
    slug: "ai-contract-review-tools",
    pillar: "ai-legal-tools",
    href: "/ai-legal-tools/ai-contract-review-tools/",
    title: "AI Contract Review Tools: Can They Replace a $300 Lawyer?",
    seoTitle: "AI Contract Review Tools: Can They Replace a $300 Lawyer? | LexAI Guide",
    metaDescription:
      "AI contract review tools promise lawyer-quality analysis for a fraction of the cost. We break down what they catch, what they miss, and when to still call a lawyer.",
    dek: "They catch missing clauses in seconds. They still can't tell you if a deal is a good idea.",
    intent: "transactional",
    keywordDifficulty: 35,
    estRpm: 48,
    status: "coming-soon",
    readingTime: 12,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,800–3,500 words",
  },
  {
    slug: "legalzoom-vs-rocket-lawyer",
    pillar: "ai-legal-tools",
    href: "/ai-legal-tools/legalzoom-vs-rocket-lawyer/",
    title: "LegalZoom vs Rocket Lawyer (2026): Honest Comparison",
    seoTitle: "LegalZoom vs Rocket Lawyer (2026): Honest Comparison | LexAI Guide",
    metaDescription:
      "LegalZoom and Rocket Lawyer solve different problems. We compare pricing, document libraries, and attorney access to help you pick the right one.",
    dek: "Same category, different business models. Here's which one fits your situation.",
    intent: "comparative",
    keywordDifficulty: 38,
    estRpm: 52,
    status: "coming-soon",
    readingTime: 11,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,800–3,500 words",
  },
  {
    slug: "donotpay-alternatives",
    pillar: "ai-legal-tools",
    href: "/ai-legal-tools/donotpay-alternatives/",
    title: "DoNotPay Alternatives That Actually Work in 2026",
    seoTitle: "DoNotPay Alternatives That Actually Work in 2026 | LexAI Guide",
    metaDescription:
      "Looking for a DoNotPay alternative? We compare the tools that actually deliver on bill disputes, subscription cancellations, and small claims filing.",
    dek: "DoNotPay isn't the only bot in town — and it isn't always the best one.",
    intent: "comparative",
    keywordDifficulty: 30,
    estRpm: 38,
    status: "coming-soon",
    readingTime: 10,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,800–3,500 words",
  },
  {
    slug: "free-ai-contract-analyzer",
    pillar: "ai-legal-tools",
    href: "/ai-legal-tools/free-ai-contract-analyzer/",
    title: "Free AI Contract Analyzers: 6 Tools, No Signup Required",
    seoTitle: "Free AI Contract Analyzers: 6 Tools, No Signup Required | LexAI Guide",
    metaDescription:
      "Six free AI tools that will scan a contract and flag risky clauses before you sign — no credit card, no account required.",
    dek: "No credit card, no account, no risky clause left unflagged.",
    intent: "transactional",
    keywordDifficulty: 20,
    estRpm: 36,
    status: "coming-soon",
    readingTime: 9,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,800–3,500 words",
  },
  {
    slug: "doola-vs-northwest-registered-agent",
    pillar: "ai-legal-tools",
    href: "/ai-legal-tools/doola-vs-northwest-registered-agent/",
    title: "Doola vs Northwest Registered Agent: Which LLC Service Wins?",
    seoTitle: "Doola vs Northwest Registered Agent: Which LLC Service Wins? | LexAI Guide",
    metaDescription:
      "Doola and Northwest Registered Agent both form LLCs — but for very different founders. Here's the honest breakdown.",
    dek: "One is built for global founders. The other is built for privacy-first Americans.",
    intent: "comparative",
    keywordDifficulty: 21,
    estRpm: 55,
    status: "coming-soon",
    readingTime: 10,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,800–3,500 words",
  },

  // ---------------------------------------------------------------- Self-Help Guides
  {
    slug: "how-to-write-demand-letter",
    pillar: "self-help-guides",
    href: "/self-help-guides/how-to-write-demand-letter/",
    title: "How to Write a Demand Letter (Free Template Included)",
    seoTitle: "How to Write a Demand Letter (Free Template Included) | LexAI Guide",
    metaDescription:
      "Learn exactly how to write a demand letter that gets results — with a free template, real examples, and the mistakes that make people ignore yours.",
    dek: "The single most underused tool for getting paid back without a lawyer.",
    intent: "informational",
    keywordDifficulty: 35,
    estRpm: 32,
    status: "published",
    readingTime: 11,
    datePublished: "2026-01-20",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,200–2,800 words",
  },
  {
    slug: "small-claims-court-guide",
    pillar: "self-help-guides",
    href: "/self-help-guides/small-claims-court-guide/",
    title: "Small Claims Court: The Complete Guide for 2026",
    seoTitle: "Small Claims Court: The Complete Guide for 2026 | LexAI Guide",
    metaDescription:
      "Everything you need to file, prepare for, and win a small claims case — from filing fees to what to say in front of the judge.",
    dek: "No lawyer required. Here's exactly how the process works, start to finish.",
    intent: "informational",
    keywordDifficulty: 38,
    estRpm: 28,
    status: "coming-soon",
    readingTime: 14,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,200–2,800 words",
  },
  {
    slug: "landlord-keeping-security-deposit",
    pillar: "self-help-guides",
    href: "/self-help-guides/landlord-keeping-security-deposit/",
    title: "Landlord Keeping Your Security Deposit? Do This First",
    seoTitle: "Landlord Keeping Your Security Deposit? Do This First | LexAI Guide",
    metaDescription:
      "Your landlord isn't returning your deposit. Here's the exact sequence — demand letter, state deadline, small claims — to get it back.",
    dek: "Before you write it off, run through this sequence — most tenants recover more than they expect.",
    intent: "informational",
    keywordDifficulty: 32,
    estRpm: 35,
    status: "published",
    readingTime: 10,
    datePublished: "2026-08-06",
    dateModified: "2026-08-06",
    appliesTo: "All States",
    wordCountTarget: "2,200–2,800 words",
  },
  {
    slug: "what-to-do-if-sued-for-debt",
    pillar: "self-help-guides",
    href: "/self-help-guides/what-to-do-if-sued-for-debt/",
    title: "Sued for Debt? Here's Exactly What to Do (Step by Step)",
    seoTitle: "Sued for Debt? Here's Exactly What to Do (Step by Step) | LexAI Guide",
    metaDescription:
      "Getting served with a debt collection lawsuit is scary, but ignoring it is the worst move. Here's your step-by-step response plan.",
    dek: "Ignoring the summons is the one move guaranteed to make this worse.",
    intent: "informational",
    keywordDifficulty: 36,
    estRpm: 42,
    status: "published",
    readingTime: 12,
    datePublished: "2026-08-06",
    dateModified: "2026-08-06",
    appliesTo: "All States",
    wordCountTarget: "2,200–2,800 words",
  },
  {
    slug: "wrongful-termination-how-to-prove",
    pillar: "self-help-guides",
    href: "/self-help-guides/wrongful-termination-how-to-prove/",
    title: "Wrongful Termination: How to Prove It and What to Do Next",
    seoTitle: "Wrongful Termination: How to Prove It and What to Do Next | LexAI Guide",
    metaDescription:
      "Fired and think it was illegal? Here's how wrongful termination actually gets proven, and the evidence to gather before you talk to anyone.",
    dek: "Being fired unfairly and being fired illegally are not the same thing — here's the difference.",
    intent: "informational",
    keywordDifficulty: 37,
    estRpm: 38,
    status: "coming-soon",
    readingTime: 12,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,200–2,800 words",
  },
  {
    slug: "demand-letter-ignored",
    pillar: "self-help-guides",
    href: "/self-help-guides/demand-letter-ignored/",
    title: "Demand Letter Ignored? Your Next 4 Legal Steps",
    seoTitle: "Demand Letter Ignored? Your Next 4 Legal Steps | LexAI Guide",
    metaDescription:
      "Sent a demand letter and heard nothing back? Here are the four moves that actually escalate a claim without hiring a lawyer.",
    dek: "Silence isn't a dead end — it's just the next step in the process.",
    intent: "informational",
    keywordDifficulty: 20,
    estRpm: 30,
    status: "coming-soon",
    readingTime: 8,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "1,600–2,200 words",
  },

  // ---------------------------------------------------------------- Know Your Rights
  {
    slug: "tenant-rights-by-state",
    pillar: "know-your-rights",
    href: "/know-your-rights/tenant-rights-by-state/",
    title: "Tenant Rights by State: What Every Renter Needs to Know",
    seoTitle: "Tenant Rights by State: What Every Renter Needs to Know | LexAI Guide",
    metaDescription:
      "Security deposits, repairs, eviction notices, and retaliation protections — how tenant rights differ by state, and where to find your state's exact rules.",
    dek: "Renting comes with more protection than most tenants realize — if you know where to look.",
    intent: "informational",
    keywordDifficulty: 33,
    estRpm: 40,
    status: "published",
    readingTime: 12,
    datePublished: "2026-02-03",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,000–2,600 words",
  },
  {
    slug: "consumer-rights-usa",
    pillar: "know-your-rights",
    href: "/know-your-rights/consumer-rights-usa/",
    title: "Your Consumer Rights in the US: The Complete 2026 Guide",
    seoTitle: "Your Consumer Rights in the US: The Complete 2026 Guide | LexAI Guide",
    metaDescription:
      "Refunds, warranties, deceptive advertising, data privacy — a plain-English breakdown of the consumer protection laws that actually apply to you.",
    dek: "The rules that protect you every time you buy something, whether you've read them or not.",
    intent: "informational",
    keywordDifficulty: 30,
    estRpm: 34,
    status: "coming-soon",
    readingTime: 13,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,000–2,600 words",
  },
  {
    slug: "employee-rights-at-work",
    pillar: "know-your-rights",
    href: "/know-your-rights/employee-rights-at-work/",
    title: "Employee Rights at Work: What Your Boss Can't Legally Do",
    seoTitle: "Employee Rights at Work: What Your Boss Can't Legally Do | LexAI Guide",
    metaDescription:
      "Overtime, breaks, discrimination, retaliation, at-will limits — the protections every US employee has, explained without the legalese.",
    dek: "At-will doesn't mean anything-goes. Here's exactly where the line sits.",
    intent: "informational",
    keywordDifficulty: 42,
    estRpm: 44,
    status: "published",
    readingTime: 13,
    datePublished: "2026-08-06",
    dateModified: "2026-08-06",
    appliesTo: "All States",
    wordCountTarget: "2,000–2,600 words",
  },
  {
    slug: "debt-collector-violations",
    pillar: "know-your-rights",
    href: "/know-your-rights/debt-collector-violations/",
    title: "FDCPA Rights: What Debt Collectors Are Legally Forbidden to Do",
    seoTitle: "FDCPA Rights: What Debt Collectors Are Legally Forbidden to Do | LexAI Guide",
    metaDescription:
      "Debt collectors can't call before 8am, threaten arrest, or contact your employer. Here's the full list of FDCPA violations — and how to report them.",
    dek: "If a collector has done any of these ten things, they've broken federal law.",
    intent: "informational",
    keywordDifficulty: 27,
    estRpm: 46,
    status: "coming-soon",
    readingTime: 10,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,000–2,600 words",
  },
  {
    slug: "how-to-remove-personal-info-internet",
    pillar: "know-your-rights",
    href: "/know-your-rights/how-to-remove-personal-info-internet/",
    title: "How to Remove Your Personal Information from the Internet",
    seoTitle: "How to Remove Your Personal Information from the Internet | LexAI Guide",
    metaDescription:
      "Data broker sites publish your address and phone number by default. Here's the opt-out process, site by site, plus the law that backs you up.",
    dek: "Data brokers publish your address by default. Here's how to make them take it down.",
    intent: "informational",
    keywordDifficulty: 24,
    estRpm: 31,
    status: "coming-soon",
    readingTime: 11,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "2,000–2,600 words",
  },

  // ---------------------------------------------------------------- Legal Templates
  {
    slug: "demand-letter-template",
    pillar: "legal-templates",
    href: "/legal-templates/demand-letter-template/",
    title: "Free Demand Letter Template (Customizable + Ready to Send)",
    seoTitle: "Free Demand Letter Template (Customizable + Ready to Send) | LexAI Guide",
    metaDescription:
      "Generate a customized demand letter in minutes. Fill in your details, preview the letter, and download it ready to print or email.",
    dek: "Fill in the blanks, preview it instantly, download it ready to send.",
    intent: "transactional",
    keywordDifficulty: 33,
    estRpm: 33,
    status: "published",
    readingTime: 6,
    datePublished: "2026-01-25",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "1,600–2,200 words",
  },
  {
    slug: "independent-contractor-agreement",
    pillar: "legal-templates",
    href: "/legal-templates/independent-contractor-agreement/",
    title: "Independent Contractor Agreement Template (Free, 2026)",
    seoTitle: "Independent Contractor Agreement Template (Free, 2026) | LexAI Guide",
    metaDescription:
      "A free, plain-English independent contractor agreement template covering scope, payment terms, IP ownership, and termination.",
    dek: "The clauses freelancers and clients both forget to put in writing.",
    intent: "transactional",
    keywordDifficulty: 34,
    estRpm: 29,
    status: "coming-soon",
    readingTime: 7,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "1,600–2,200 words",
  },
  {
    slug: "cease-and-desist-letter",
    pillar: "legal-templates",
    href: "/legal-templates/cease-and-desist-letter/",
    title: "Cease and Desist Letter Template: Free + Step-by-Step Guide",
    seoTitle: "Cease and Desist Letter Template: Free + Step-by-Step Guide | LexAI Guide",
    metaDescription:
      "Stop harassment, IP infringement, or defamation with a properly worded cease and desist letter. Free template plus delivery instructions.",
    dek: "A firm letter, sent the right way, resolves more disputes than people expect.",
    intent: "transactional",
    keywordDifficulty: 32,
    estRpm: 27,
    status: "coming-soon",
    readingTime: 8,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "1,600–2,200 words",
  },
  {
    slug: "nda-template",
    pillar: "legal-templates",
    href: "/legal-templates/nda-template/",
    title: "NDA Template in Plain English: Free Non-Disclosure Agreement",
    seoTitle: "NDA Template in Plain English: Free Non-Disclosure Agreement | LexAI Guide",
    metaDescription:
      "A free mutual NDA template written in plain English, covering confidential information, exclusions, and term length.",
    dek: "Confidentiality terms that protect you without eighteen pages of boilerplate.",
    intent: "transactional",
    keywordDifficulty: 26,
    estRpm: 25,
    status: "coming-soon",
    readingTime: 6,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "1,600–2,200 words",
  },
  {
    slug: "llc-operating-agreement",
    pillar: "legal-templates",
    href: "/legal-templates/llc-operating-agreement/",
    title: "LLC Operating Agreement Template: Free Download 2026",
    seoTitle: "LLC Operating Agreement Template: Free Download 2026 | LexAI Guide",
    metaDescription:
      "A free LLC operating agreement template covering ownership splits, voting rights, and profit distribution — for single- and multi-member LLCs.",
    dek: "The document your state probably doesn't require but your LLC definitely needs.",
    intent: "transactional",
    keywordDifficulty: 31,
    estRpm: 37,
    status: "coming-soon",
    readingTime: 8,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "1,600–2,200 words",
  },

  // ---------------------------------------------------------------- Calculators
  {
    slug: "small-claims-limit",
    pillar: "calculators",
    href: "/calculators/small-claims-limit/",
    title: "Small Claims Limit by State Calculator",
    seoTitle: "Small Claims Limit by State Calculator | LexAI Guide",
    metaDescription:
      "Find your state's small claims court dollar limit instantly, plus the court name and where to file.",
    dek: "Pick your state, get the exact dollar ceiling and where to file.",
    intent: "transactional",
    keywordDifficulty: 18,
    estRpm: 30,
    status: "published",
    readingTime: 3,
    datePublished: "2026-01-15",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "Tool",
  },
  {
    slug: "overtime-pay",
    pillar: "calculators",
    href: "/calculators/overtime-pay/",
    title: "Overtime Pay Calculator",
    seoTitle: "Overtime Pay Calculator (FLSA) | LexAI Guide",
    metaDescription:
      "Calculate how much overtime pay you're owed under the FLSA based on your hourly wage, hours worked, and state.",
    dek: "See exactly what you're owed under federal overtime law.",
    intent: "transactional",
    keywordDifficulty: 22,
    estRpm: 35,
    status: "published",
    readingTime: 3,
    datePublished: "2026-02-10",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "Tool",
  },
  {
    slug: "security-deposit-checker",
    pillar: "calculators",
    href: "/calculators/security-deposit-checker/",
    title: "Security Deposit Deduction Checker",
    seoTitle: "Security Deposit Deduction Checker | LexAI Guide",
    metaDescription:
      "Check whether your landlord's security deposit deductions are legal in your state, and what to do if they aren't.",
    dek: "Enter the numbers, find out if the deduction is legal.",
    intent: "transactional",
    keywordDifficulty: 19,
    estRpm: 33,
    status: "published",
    readingTime: 3,
    datePublished: "2026-08-06",
    dateModified: "2026-08-06",
    appliesTo: "All States",
    wordCountTarget: "Tool",
  },
  {
    slug: "statute-of-limitations",
    pillar: "calculators",
    href: "/calculators/statute-of-limitations/",
    title: "Statute of Limitations Checker",
    seoTitle: "Statute of Limitations Checker | LexAI Guide",
    metaDescription:
      "Find out how much time you have left to file a claim based on your state and case type.",
    dek: "Find your filing deadline before it finds you.",
    intent: "transactional",
    keywordDifficulty: 23,
    estRpm: 34,
    status: "coming-soon",
    readingTime: 3,
    datePublished: "2026-08-01",
    dateModified: "2026-08-01",
    appliesTo: "All States",
    wordCountTarget: "Tool",
  },
];

export function getArticle(pillar: string, slug: string): ArticleMeta | undefined {
  return ARTICLES.find((a) => a.pillar === pillar && a.slug === slug);
}

export function getArticlesByPillar(pillar: string): ArticleMeta[] {
  return ARTICLES.filter((a) => a.pillar === pillar);
}

/**
 * Published articles first, plus at most `maxComingSoon` roadmap teasers
 * — so a pillar with a long "coming soon" backlog doesn't visually read
 * as mostly unfinished. `hiddenCount` tells the page how many more are
 * still in the works, for an honest "+N more guides in progress" note.
 */
export function getPillarArticlesForDisplay(
  pillar: string,
  maxComingSoon = 2
): { articles: ArticleMeta[]; hiddenCount: number } {
  const all = getArticlesByPillar(pillar);
  const published = all.filter((a) => a.status === "published");
  const comingSoon = all.filter((a) => a.status === "coming-soon");
  return {
    articles: [...published, ...comingSoon.slice(0, maxComingSoon)],
    hiddenCount: Math.max(comingSoon.length - maxComingSoon, 0),
  };
}

export function getPublishedArticles(): ArticleMeta[] {
  return ARTICLES.filter((a) => a.status === "published");
}

export function getLatestArticles(limit = 6): ArticleMeta[] {
  return ARTICLES.filter((a) => a.status === "published")
    .sort((a, b) => (a.datePublished < b.datePublished ? 1 : -1))
    .slice(0, limit);
}
