import type { StateData } from "./types";

/**
 * Reference figures only — compiled from commonly published state-court and
 * statutory summaries. Small claims limits, notice periods, and limitations
 * periods change by legislative session and by exact claim type. Always
 * confirmed against the user's local court/statute before acting — see the
 * disclaimer rendered on every page that uses this data.
 * Last verified: 2026-01.
 */
export const STATES: StateData[] = [
  { slug: "alabama", name: "Alabama", abbr: "AL", priority: false, smallClaimsLimit: 6000, smallClaimsCourtName: "Small Claims Court (District Court)", securityDepositDeadlineDays: 60, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 7, summary: "Alabama's small claims process runs through district court and is designed for self-represented filers." },
  { slug: "alaska", name: "Alaska", abbr: "AK", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Court (District Court)", securityDepositDeadlineDays: 14, statuteOfLimitationsContractYears: 3, atWillException: false, tenantNoticeToQuitDays: 7, summary: "Alaska requires a fast 14-day security deposit turnaround when a tenant leaves no forwarding dispute." },
  { slug: "arizona", name: "Arizona", abbr: "AZ", priority: true, smallClaimsLimit: 3500, smallClaimsCourtName: "Small Claims Division, Justice Court", securityDepositDeadlineDays: 14, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 5, summary: "Arizona's Justice Courts handle small claims with one of the lowest dollar ceilings in the country, keeping cases fast." },
  { slug: "arkansas", name: "Arkansas", abbr: "AR", priority: false, smallClaimsLimit: 5000, smallClaimsCourtName: "Small Claims Division, District Court", securityDepositDeadlineDays: 60, statuteOfLimitationsContractYears: 5, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Arkansas gives landlords and tenants a notably short unlawful-detainer timeline compared to neighboring states." },
  { slug: "california", name: "California", abbr: "CA", priority: true, smallClaimsLimit: 12500, smallClaimsCourtName: "Small Claims Court (Superior Court)", securityDepositDeadlineDays: 21, statuteOfLimitationsContractYears: 4, atWillException: false, tenantNoticeToQuitDays: 3, summary: "California pairs a high small claims ceiling with some of the country's strongest tenant and worker protections." },
  { slug: "colorado", name: "Colorado", abbr: "CO", priority: false, smallClaimsLimit: 7500, smallClaimsCourtName: "Small Claims Court (County Court)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 10, summary: "Colorado's security deposit deadline can extend to 60 days if the lease says so in writing." },
  { slug: "connecticut", name: "Connecticut", abbr: "CT", priority: false, smallClaimsLimit: 5000, smallClaimsCourtName: "Small Claims Session, Superior Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Connecticut requires deposit refunds within 30 days or 15 days of receiving a forwarding address, whichever is later." },
  { slug: "delaware", name: "Delaware", abbr: "DE", priority: false, smallClaimsLimit: 25000, smallClaimsCourtName: "Court of Common Pleas", securityDepositDeadlineDays: 20, statuteOfLimitationsContractYears: 3, atWillException: false, tenantNoticeToQuitDays: 7, summary: "Delaware's civil claim ceiling is unusually high, letting more disputes skip a lawyer entirely." },
  { slug: "florida", name: "Florida", abbr: "FL", priority: true, smallClaimsLimit: 8000, smallClaimsCourtName: "County Court, Small Claims Division", securityDepositDeadlineDays: 15, statuteOfLimitationsContractYears: 5, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Florida landlords must send written deposit intent within 30 days and pay out within 15 if undisputed." },
  { slug: "georgia", name: "Georgia", abbr: "GA", priority: true, smallClaimsLimit: 15000, smallClaimsCourtName: "Magistrate Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Georgia's Magistrate Court handles a broad small claims ceiling with simplified, no-lawyer-required procedure." },
  { slug: "hawaii", name: "Hawaii", abbr: "HI", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Division, District Court", securityDepositDeadlineDays: 14, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 5, summary: "Hawaii tenants get one of the fastest deposit-return windows in the country at 14 days." },
  { slug: "idaho", name: "Idaho", abbr: "ID", priority: false, smallClaimsLimit: 5000, smallClaimsCourtName: "Small Claims Department, Magistrate Court", securityDepositDeadlineDays: 21, statuteOfLimitationsContractYears: 5, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Idaho defaults to a 21-day deposit return unless the lease sets a different reasonable timeline." },
  { slug: "illinois", name: "Illinois", abbr: "IL", priority: true, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Court (Circuit Court)", securityDepositDeadlineDays: 45, statuteOfLimitationsContractYears: 10, atWillException: false, tenantNoticeToQuitDays: 5, summary: "Illinois gives a long 10-year window to sue on written contracts, among the longest in the nation." },
  { slug: "indiana", name: "Indiana", abbr: "IN", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Court", securityDepositDeadlineDays: 45, statuteOfLimitationsContractYears: 10, atWillException: false, tenantNoticeToQuitDays: 10, summary: "Indiana landlords have 45 days to itemize deductions or return the full deposit." },
  { slug: "iowa", name: "Iowa", abbr: "IA", priority: false, smallClaimsLimit: 6500, smallClaimsCourtName: "Small Claims Court (District Court)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 10, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Iowa's small claims division is designed to resolve most cases in a single hearing." },
  { slug: "kansas", name: "Kansas", abbr: "KS", priority: false, smallClaimsLimit: 4000, smallClaimsCourtName: "Small Claims Procedure Act Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 5, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Kansas keeps its small claims ceiling modest, which pushes larger disputes into limited civil court." },
  { slug: "kentucky", name: "Kentucky", abbr: "KY", priority: false, smallClaimsLimit: 2500, smallClaimsCourtName: "Small Claims Division, District Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 10, atWillException: false, tenantNoticeToQuitDays: 7, summary: "Kentucky has one of the lowest small claims ceilings in the country at $2,500." },
  { slug: "louisiana", name: "Louisiana", abbr: "LA", priority: false, smallClaimsLimit: 5000, smallClaimsCourtName: "Small Claims Division, City/Parish Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 10, atWillException: false, tenantNoticeToQuitDays: 5, summary: "Louisiana follows civil-law contract rules that differ from most other states — read the fine print." },
  { slug: "maine", name: "Maine", abbr: "ME", priority: false, smallClaimsLimit: 6000, smallClaimsCourtName: "Small Claims Court (District Court)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 7, summary: "Maine tightens the deposit-return window to 21 days for tenancies-at-will." },
  { slug: "maryland", name: "Maryland", abbr: "MD", priority: false, smallClaimsLimit: 5000, smallClaimsCourtName: "Small Claims, District Court", securityDepositDeadlineDays: 45, statuteOfLimitationsContractYears: 3, atWillException: false, tenantNoticeToQuitDays: 30, summary: "Maryland landlords who miss the 45-day deposit deadline can owe up to triple damages." },
  { slug: "massachusetts", name: "Massachusetts", abbr: "MA", priority: false, smallClaimsLimit: 7000, smallClaimsCourtName: "Small Claims Session, District Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 14, summary: "Massachusetts has some of the strictest security-deposit paperwork rules in the country." },
  { slug: "michigan", name: "Michigan", abbr: "MI", priority: false, smallClaimsLimit: 6500, smallClaimsCourtName: "Small Claims Division, District Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 7, summary: "Michigan requires landlords to provide an itemized list of damages within 30 days of move-out." },
  { slug: "minnesota", name: "Minnesota", abbr: "MN", priority: false, smallClaimsLimit: 15000, smallClaimsCourtName: "Conciliation Court", securityDepositDeadlineDays: 21, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 14, summary: "Minnesota's Conciliation Court has one of the highest small claims ceilings nationwide." },
  { slug: "mississippi", name: "Mississippi", abbr: "MS", priority: false, smallClaimsLimit: 3500, smallClaimsCourtName: "Small Claims, Justice Court", securityDepositDeadlineDays: 45, statuteOfLimitationsContractYears: 3, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Mississippi's Justice Court hears small claims without formal rules of evidence." },
  { slug: "missouri", name: "Missouri", abbr: "MO", priority: false, smallClaimsLimit: 5000, smallClaimsCourtName: "Small Claims Court (Circuit Court)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 10, atWillException: false, tenantNoticeToQuitDays: 30, summary: "Missouri gives tenants a full 30 days after move-out before a deposit dispute can proceed." },
  { slug: "montana", name: "Montana", abbr: "MT", priority: false, smallClaimsLimit: 7000, smallClaimsCourtName: "Small Claims Court (Justice Court)", securityDepositDeadlineDays: 10, statuteOfLimitationsContractYears: 8, atWillException: true, tenantNoticeToQuitDays: 3, summary: "Montana is the only state that limits at-will firing after a probation period under its Wrongful Discharge Act." },
  { slug: "nebraska", name: "Nebraska", abbr: "NE", priority: false, smallClaimsLimit: 3900, smallClaimsCourtName: "Small Claims Court (County Court)", securityDepositDeadlineDays: 14, statuteOfLimitationsContractYears: 5, atWillException: false, tenantNoticeToQuitDays: 7, summary: "Nebraska sets one of the shortest security-deposit return windows in the country at 14 days." },
  { slug: "nevada", name: "Nevada", abbr: "NV", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Court (Justice Court)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 7, summary: "Nevada raised its small claims ceiling to $10,000, opening the door to bigger self-filed disputes." },
  { slug: "new-hampshire", name: "New Hampshire", abbr: "NH", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Session, Circuit Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 3, atWillException: false, tenantNoticeToQuitDays: 7, summary: "New Hampshire caps deposits at one month's rent for most tenancies, capped further for larger complexes." },
  { slug: "new-jersey", name: "New Jersey", abbr: "NJ", priority: false, smallClaimsLimit: 5000, smallClaimsCourtName: "Special Civil Part, Small Claims Section", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 30, summary: "New Jersey requires deposits to sit in an interest-bearing account, with interest owed back to tenants." },
  { slug: "new-mexico", name: "New Mexico", abbr: "NM", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Division, Magistrate Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 3, summary: "New Mexico's 30-day deposit rule shortens to 30 days flat regardless of dispute status." },
  { slug: "new-york", name: "New York", abbr: "NY", priority: true, smallClaimsLimit: 5000, smallClaimsCourtName: "Small Claims Part, City/Town/Village Court", securityDepositDeadlineDays: 14, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 14, summary: "New York tightened its deposit-return deadline to 14 days statewide under 2019 tenant-protection reforms." },
  { slug: "north-carolina", name: "North Carolina", abbr: "NC", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Court (Magistrate)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 3, atWillException: false, tenantNoticeToQuitDays: 10, summary: "North Carolina magistrates hear small claims informally, often resolving cases the same day." },
  { slug: "north-dakota", name: "North Dakota", abbr: "ND", priority: false, smallClaimsLimit: 15000, smallClaimsCourtName: "Small Claims Court (District Court)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 3, summary: "North Dakota's small claims ceiling ranks among the highest in the country." },
  { slug: "ohio", name: "Ohio", abbr: "OH", priority: true, smallClaimsLimit: 6000, smallClaimsCourtName: "Small Claims Division, Municipal Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Ohio landlords who wrongfully withhold a deposit can owe double damages plus attorney fees." },
  { slug: "oklahoma", name: "Oklahoma", abbr: "OK", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Procedure, District Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 5, atWillException: false, tenantNoticeToQuitDays: 5, summary: "Oklahoma's small claims track moves fast, typically resolving within a few weeks of filing." },
  { slug: "oregon", name: "Oregon", abbr: "OR", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Department, Circuit Court", securityDepositDeadlineDays: 31, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 10, summary: "Oregon requires a detailed written accounting within 31 days of move-out, one of the strictest formats." },
  { slug: "pennsylvania", name: "Pennsylvania", abbr: "PA", priority: true, smallClaimsLimit: 12000, smallClaimsCourtName: "Magisterial District Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 4, atWillException: false, tenantNoticeToQuitDays: 15, summary: "Pennsylvania's Magisterial District Courts handle small claims cost-effectively without formal filing fees." },
  { slug: "rhode-island", name: "Rhode Island", abbr: "RI", priority: false, smallClaimsLimit: 2500, smallClaimsCourtName: "Small Claims Court (District Court)", securityDepositDeadlineDays: 20, statuteOfLimitationsContractYears: 10, atWillException: false, tenantNoticeToQuitDays: 5, summary: "Rhode Island keeps one of the lowest small claims ceilings alongside a fast 20-day deposit rule." },
  { slug: "south-carolina", name: "South Carolina", abbr: "SC", priority: false, smallClaimsLimit: 7500, smallClaimsCourtName: "Magistrate Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 3, atWillException: false, tenantNoticeToQuitDays: 5, summary: "South Carolina Magistrate Courts handle the bulk of consumer and landlord-tenant small claims." },
  { slug: "south-dakota", name: "South Dakota", abbr: "SD", priority: false, smallClaimsLimit: 12000, smallClaimsCourtName: "Small Claims Court (Magistrate Court)", securityDepositDeadlineDays: 14, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 3, summary: "South Dakota pairs a high small claims ceiling with one of the shortest deposit-return windows." },
  { slug: "tennessee", name: "Tennessee", abbr: "TN", priority: false, smallClaimsLimit: 25000, smallClaimsCourtName: "General Sessions Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 14, summary: "Tennessee's General Sessions Court allows claims up to $25,000 without a formal civil suit." },
  { slug: "texas", name: "Texas", abbr: "TX", priority: true, smallClaimsLimit: 20000, smallClaimsCourtName: "Justice Court (Small Claims Cases)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 4, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Texas Justice Courts allow claims up to $20,000, among the highest self-filing ceilings in the country." },
  { slug: "utah", name: "Utah", abbr: "UT", priority: false, smallClaimsLimit: 11000, smallClaimsCourtName: "Small Claims Court (Justice/District Court)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Utah landlords must return deposits within 30 days of the later of move-out or receiving an address." },
  { slug: "vermont", name: "Vermont", abbr: "VT", priority: false, smallClaimsLimit: 5000, smallClaimsCourtName: "Small Claims Procedure, Superior Court", securityDepositDeadlineDays: 14, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 14, summary: "Vermont's 14-day deposit deadline is one of the fastest in New England." },
  { slug: "virginia", name: "Virginia", abbr: "VA", priority: false, smallClaimsLimit: 5000, smallClaimsCourtName: "Small Claims Division, General District Court", securityDepositDeadlineDays: 45, statuteOfLimitationsContractYears: 5, atWillException: false, tenantNoticeToQuitDays: 5, summary: "Virginia gives landlords a full 45 days to itemize and return a security deposit." },
  { slug: "washington", name: "Washington", abbr: "WA", priority: true, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Department, District Court", securityDepositDeadlineDays: 21, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 14, summary: "Washington requires a full accounting within 21 days and doubles damages for bad-faith withholding." },
  { slug: "west-virginia", name: "West Virginia", abbr: "WV", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Magistrate Court", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 10, atWillException: false, tenantNoticeToQuitDays: 30, summary: "West Virginia Magistrate Courts provide a low-cost forum for consumer and rental disputes alike." },
  { slug: "wisconsin", name: "Wisconsin", abbr: "WI", priority: false, smallClaimsLimit: 10000, smallClaimsCourtName: "Small Claims Court (Circuit Court)", securityDepositDeadlineDays: 21, statuteOfLimitationsContractYears: 6, atWillException: false, tenantNoticeToQuitDays: 5, summary: "Wisconsin requires itemized deposit deductions within 21 days, among the strictest in the Midwest." },
  { slug: "wyoming", name: "Wyoming", abbr: "WY", priority: false, smallClaimsLimit: 6000, smallClaimsCourtName: "Small Claims Court (Circuit Court)", securityDepositDeadlineDays: 30, statuteOfLimitationsContractYears: 10, atWillException: false, tenantNoticeToQuitDays: 3, summary: "Wyoming defaults to a 30-day deposit return with no statutory penalty unless the lease specifies one." },
];

export function getStateBySlug(slug: string): StateData | undefined {
  return STATES.find((s) => s.slug === slug);
}

export const PRIORITY_STATES = STATES.filter((s) => s.priority);

/**
 * 50-state medians, used to give each state page genuine comparative
 * context ("above the national median of...") instead of just
 * restating that state's own numbers in isolation.
 */
export const NATIONAL_MEDIANS = {
  smallClaimsLimit: 7500,
  securityDepositDeadlineDays: 30,
  statuteOfLimitationsContractYears: 6,
  tenantNoticeToQuitDays: 5,
} as const;

export function formatUsd(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(amount);
}
