import type { Metadata } from "next";

export const metadata: Metadata = {
  title: { absolute: "Terms of Use | LexAI Guide" },
  description: "The terms that govern your use of LexAI Guide.",
  alternates: { canonical: "/terms-of-use/" },
};

export default function Page() {
  return (
    <div className="container-page py-14 md:py-20">
      <div className="article-prose max-w-2xl">
        <p className="text-caption-mono text-ink-soft">Last updated: August 1, 2026</p>
        <h1 className="text-display-h1 mb-6 text-ink">Terms of Use</h1>

        <p>
          By using lexaiguide.com, you agree to these terms. If you
          don&rsquo;t agree, please don&rsquo;t use the site.
        </p>

        <h2>Not Legal Advice</h2>
        <p>
          LexAI Guide provides general legal information for educational
          purposes only. Nothing on this site constitutes legal advice, and
          using it does not create an attorney-client relationship between
          you and LexAI Guide or any of its contributors. Laws change and
          vary by jurisdiction — always confirm anything important with a
          licensed attorney before acting.
        </p>

        <h2>Templates &amp; Calculators</h2>
        <p>
          Documents generated by our template tools and figures produced by
          our calculators are starting points, not guarantees of legal
          accuracy or outcome. You&rsquo;re responsible for reviewing any
          generated document before relying on it, and for confirming
          calculator results against your local court or statute.
        </p>

        <h2>Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the site for any unlawful purpose.</li>
          <li>Attempt to interfere with the site&rsquo;s normal operation.</li>
          <li>Scrape or republish our content without permission.</li>
          <li>Misrepresent content on this site as official legal advice from a licensed attorney.</li>
        </ul>

        <h2>Third-Party Services</h2>
        <p>
          We link to and review third-party tools (LegalZoom, Rocket Lawyer,
          and others). We don&rsquo;t control those services and
          aren&rsquo;t responsible for their content, pricing, or
          performance. Some links are affiliate links — see our{" "}
          <a href="/affiliate-disclosure/">Affiliate Disclosure</a>.
        </p>

        <h2>Disclaimer of Warranties</h2>
        <p>
          This site is provided &ldquo;as is&rdquo; without warranties of
          any kind. We do our best to keep information accurate and current
          but make no guarantees about completeness or accuracy.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, LexAI Guide is not liable
          for any damages arising from your use of this site or reliance on
          its content.
        </p>

        <h2>Changes to These Terms</h2>
        <p>
          We may update these terms from time to time. Continued use of the
          site after changes means you accept the updated terms.
        </p>

        <h2>Contact Us</h2>
        <p>
          Questions? Email{" "}
          <a href="mailto:hello@lexaiguide.com">hello@lexaiguide.com</a>.
        </p>
      </div>
    </div>
  );
}
